# Generated by Django 2.2 on 2021-06-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aisi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('aisi_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='aisi_app.Message_Post')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aisi_app.User')),
            ],
        ),
    ]
