# Generated by Django 2.2 on 2021-06-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aisi_app', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISI_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='liked_posts', to='aisi_app.User')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='aisi_app.User')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='aisi_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='aisi_app.AISI_Post'),
        ),
        migrations.DeleteModel(
            name='Message_Post',
        ),
    ]
